name: Model Retraining Workflow

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_DATA_PATH: ${{ secrets.REMOTE_DATA_PATH }}
      REMOTE_MODEL_PATH: ${{ secrets.REMOTE_MODEL_PATH }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

    - name: Download latest trade data
      run: |
        scp $REMOTE_USER@$REMOTE_HOST:$REMOTE_DATA_PATH/trade_data.csv ./data/

    - name: Retrain model
      run: |
        python -c "from agents.signal_optimizer import SignalOptimizer; optimizer = SignalOptimizer(); optimizer.optimize_model()"
      env:
        MODEL_UPDATE_FORCE: true

    - name: Upload updated model
      run: |
        scp ./models/current_model.pkl $REMOTE_USER@$REMOTE_HOST:$REMOTE_MODEL_PATH

    - name: Send success notification
      if: success()
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_API_KEY/sendMessage" \
        -d chat_id="$TELEGRAM_CHAT_ID" \
        -d text="✅ Model retraining successful! New model deployed to production." \
        -d parse_mode="HTML"

    - name: Send failure notification
      if: failure()
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_API_KEY/sendMessage" \
        -d chat_id="$TELEGRAM_CHAT_ID" \
        -d text="❌ Model retraining failed! Please check workflow logs." \
        -d parse_mode="HTML"

    - name: Commit updated model (optional)
      if: success()
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add models/current_model.pkl
        git commit -m "[Automated] Update trading model" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }} || echo "No changes to push"
